webmappsrl/wm-core

projects/wm-core/src/services/geolocation.service.ts
- Refactored the _watcher property in GeolocationService to include type and id
- Updated start() and stopRecording() methods to use the new _watcher structure
- Added a new private method, _backgroundGeolocationWatcher(), to handle background geolocation tracking
- Created a new private method, _clearCurrentWatcher(), to clear the current watcher based on its type
- Removed the _nativeWatcher() method as it is no longer needed
- Modified the _webWatcher() method to update the _watcher property with the correct type and id
=> chore: Update geolocation.service.ts oc: 4166

projects/wm-core/src/profile/profile-user/profile-user.component.html, projects/wm-core/src/profile/profile-user/profile-user.component.ts
The deleteUserAlert method and its dependencies have been removed from the ProfileUserComponent.
=> chore: Remove deleteUserAlert method and related imports oc: 4117

projects/wm-core/src/services/geolocation.service.ts, projects/wm-core/src/services/ugc.service.ts, projects/wm-core/src/utils/localForage.ts
- In the GeolocationService, initialize _recordedFeature with an empty WmFeature object.
- In the UgcService, update the API endpoints for saving poi and track to use "/v2" suffix.
- In the localForage utility, update the filter condition to include media with matching ids.
These changes ensure proper functionality and compatibility with the latest requirements.
=> chore: Update geolocation and ugc services oc: 4247

projects/wm-core/src/utils/localForage.ts
This commit adds the functionality to save UGC media for UGC tracks. It retrieves the photos from the feature properties and saves each photo using the saveUgcMedia function. This ensures that all associated media is properly saved along with the track data.
=> chore: Add saving UGC media for UGC tracks oc: 4247

projects/wm-core/src/store/features/ugc/ugc.actions.ts, projects/wm-core/src/store/features/ugc/ugc.effects.ts, projects/wm-core/src/store/features/ugc/ugc.reducer.ts, projects/wm-core/src/store/features/ugc/ugc.selector.ts, projects/wm-core/src/utils/localForage.ts
This commit adds the following actions to the UGC feature:
- enableSyncInterval
- disableSyncInterval
- deleteUgcTrack
- deleteUgcTrackSuccess
- deleteUgcTrackFailure
- deleteUgcPoi
- deleteUgcPoiSuccess
- deleteUgcPoiFailure
These actions allow for enabling/disabling the sync interval, deleting UGC tracks and POIs, and handling success/failure scenarios.
=> feat(ugc): add deleteUgcTrack and deleteUgcPoi actions oc: 4454

projects/wm-core/src/map/map.component.ts, projects/wm-core/src/store/auth/auth.reducer.ts, projects/wm-core/src/store/auth/auth.selectors.ts, projects/wm-core/src/store/user-activity/user-activity.action.ts, projects/wm-core/src/store/user-activity/user-activity.reducer.ts, projects/wm-core/src/store/user-activity/user-activity.selector.ts
This commit updates the user-activity action file by adding two new actions: startLoader and stopLoader. It also modifies the reducer to handle these actions and update the loading state accordingly. Additionally, the selector file is updated to include a new selector for the loading state.
chore: Remove loading property from auth reducer and selectors
The loading property in the auth reducer and selectors has been removed as it is no longer needed. This change simplifies the code and improves performance.
chore(map): add loader start and stop functionality
This commit adds the functionality to start and stop the loader in the map component. The loader is started when rendering a layer or rendering pois starts, and it is stopped when rendering a layer or rendering pois is done.
=> chore: Update user-activity actions, reducer, and selector oc: 4491

projects/wm-core/src/profile/profile-records/profile-records.component.html, projects/wm-core/src/profile/profile-records/profile-records.component.ts, projects/wm-core/src/services/url-handler.service.ts, projects/wm-core/src/store/features/ugc/ugc.effects.ts, projects/wm-core/src/utils/localForage.ts
This commit adds two new functions, `getLastSynchronizedUgcPoi` and `getLastSynchronizedUgcTrack`, to the `localForage.ts` file in the `utils` directory. These functions retrieve the last synchronized UGC (User-Generated Content) POI and track respectively. If there are no synchronized items, they return null. Error handling is also implemented in case of any failures.
Additionally, the existing function `getUgcPoi` is modified to handle a null value for the `poiId` parameter. It now returns the last synchronized UGC POI if available, followed by the device UGC POI, and finally falls back to returning the last synchronized UGC POI using the new function.
The existing function `getUgcTrack` is also modified to include retrieving the last synchronized UGC track using the new function.
These …
=> chore(utils): add functions to get last synchronized UGC POI and track oc: 4611

projects/wm-core/src/store/features/ugc/ugc.effects.ts, projects/wm-core/src/store/features/ugc/ugc.reducer.ts, projects/wm-core/src/ugc-poi-properties/ugc-poi-properties.component.html, projects/wm-core/src/ugc-poi-properties/ugc-poi-properties.component.ts
- Updated the code in `ugc.effects.ts` to handle errors when updating UGC POI.
- Updated the code in `ugc.reducer.ts` to handle successful deletion and update of UGC POI.
- Modified the HTML template in `ugc-poi-properties.component.html` to reflect changes in button labels and function calls for deleting and updating UGC POI.
- Modified the TypeScript file in `ugc-poi-properties.component.ts` to handle deletion and updating of UGC POI, including confirmation alerts.
These changes allow users to update properties of a UGC Point of Interest (POI) and delete a specific UGC POI.
=> fix(ugc): update UGC POI properties and delete functionality oc: 4656

projects/wm-core/src/box/box.ts, projects/wm-core/src/box/ugc-box/ugc-box.component.html, projects/wm-core/src/box/ugc-box/ugc-box.component.scss, projects/wm-core/src/box/ugc-box/ugc-box.component.ts, projects/wm-core/src/localization/i18n/de.ts, projects/wm-core/src/localization/i18n/en.ts, projects/wm-core/src/localization/i18n/es.ts, projects/wm-core/src/localization/i18n/fr.ts, projects/wm-core/src/localization/i18n/it.ts, projects/wm-core/src/localization/i18n/pr.ts, projects/wm-core/src/modal-ugc-track-uploader/modal-ugc-track-uploader.component.html, projects/wm-core/src/modal-ugc-track-uploader/modal-ugc-track-uploader.component.scss, projects/wm-core/src/modal-ugc-track-uploader/modal-ugc-track-uploader.component.ts, projects/wm-core/src/store/user-activity/user-activity.action.ts, projects/wm-core/src/store/user-activity/user-activity.effects.ts, projects/wm-core/src/wm-core.module.ts
This commit adds the modal-ugc-track-uploader component, which allows users to upload track files in various formats such as GPX, KML, and GeoJSON. The component includes HTML, SCSS, and TypeScript files that handle file selection, drag and drop functionality, validation of file types, reading file content, and converting it into a WmFeature object. Users can cancel the upload process or proceed with uploading the selected track file.
chore(ugc-box): Add UGC uploader button
- Added an import statement for the `Store` from `@ngrx/store`
- Added a new parameter `_store` of type `Store` to the constructor
- Added a new method `openUgcUploader()` that dispatches the `openUgcUploader()` action
- Updated the HTML template to include an `<ion-button>` element with an icon for uploading UGC
- …
=> chore: Add modal-ugc-track-uploader component oc: 4669

projects/wm-core/src/store/conf/conf.selector.ts, projects/wm-core/src/store/user-activity/user-activity.selector.ts, projects/wm-core/src/track-properties/track-properties.component.html, projects/wm-core/src/track-properties/track-properties.component.ts
This commit adds the functionality to display the flow line quote text in the track properties component. The flow line quote text is calculated based on the altitude of the location and certain threshold values. The text will be displayed dynamically based on the altitude value.
The following files were modified:
- projects/wm-core/src/store/conf/conf.selector.ts
- projects/wm-core/src/store/user-activity/user-activity.selector.ts
- projects/wm-core/src/track-properties/track-properties.component.html
- projects/wm-core/src/track-properties/track-properties.component.ts
=> chore(conf): add flow line quote text to track properties oc:4740,4745,4739,4741,4727

projects/wm-core/src/box/poi-box/poi-box.component.html, projects/wm-core/src/box/poi-box/poi-box.component.scss, projects/wm-core/src/box/poi-box/poi-box.component.ts, projects/wm-core/src/box/search-box/search-box.component.html, projects/wm-core/src/box/search-box/search-box.component.scss, projects/wm-core/src/box/search-box/search-box.component.ts, projects/wm-core/src/home/home-result/home-result.component.html, projects/wm-core/src/shared/shared.module.ts, projects/wm-core/src/shared/ugc-synchronized-badge/ugc-synchronized-badge.component.ts, projects/wm-core/src/shared/ugc-synchronized/ugc-synchronized.component.ts
- Added UgcSynchronizedComponent to the shared module
- UgcSynchronizedComponent displays an icon based on the presence of an ID in properties
chore(search-box): add ugc-synchronized component
- Added the `wm-ugc-synchronized` component to the search box template.
- Positioned the `wm-ugc-synchronized` component in the top right corner of the search box.
- Imported and used the `ugcOpened` selector from `@wm-core/store/user-activity/user-activity.selector`.
- Created an observable `ugcOpened$` to track whether UGC (User Generated Content) is opened or not.
chore: Update poi-box component
- Added wm-ugc-synchronized element to the HTML template
- Updated styling in the SCSS file
- Added ugcOpened$ observable to the TypeScript file
=> chore: add UgcSynchronizedComponent oc: 4776

projects/wm-core/src/store/auth/auth.effects.ts, projects/wm-core/src/utils/localForage.ts
- Added import for IUser from '@wm-core/store/auth/auth.model'
- Added getAuth() function to retrieve user authentication information
- Added removeAuth() function to remove user authentication information
- Added saveAuth() function to save user authentication information
- Created deviceAuth localforage instance for storing authentication data
chore: Update auth.effects.ts
- Refactored imports in auth.effects.ts
- Added saveAuth() function calls after successful login, sign up, and getUser()
- Added removeAuth() function call after sign out
- Updated error handling in loadAuthsFailure action to check for existing user data before dispatching failure action
=> chore: Update localForage.ts oc: 4772

projects/wm-core/src/ugc-track-properties/ugc-track-properties.component.ts
This commit removes unused imports and an unused event emitter in the UgcTrackPropertiesComponent. The imports for ActivatedRoute and Router are no longer needed, and the trackElevationChartHover event emitter is no longer used.
=> chore: Remove unused imports and event emitter oc: 4820

projects/wm-core/src/store/user-activity/user-activity.selector.ts
The code change fixes a null check in the user-activity.selector.ts file. The previous code did not handle null values correctly, causing potential issues. This fix ensures that the length of arrays is properly checked before performing comparisons.
=> fix: Fix null check in user-activity.selector.ts oc: 4815

projects/wm-core/src/modal-ugc-track-uploader/modal-ugc-track-uploader.component.html, projects/wm-core/src/modal-ugc-track-uploader/modal-ugc-track-uploader.component.ts
- Updated the accepted file types in the HTML template to include GPX, KML, and GeoJSON formats.
- Updated the accepted file types in the TypeScript file to include additional MIME types for GPX, KML, and GeoJSON files.
=> chore: Update UGC track uploader component oc: 4822

projects/wm-core/src/services/geolocation.service.ts
This commit adds the altitude parameter to the coordinates array of the recorded feature in the GeolocationService. It also updates the locations array in the properties of the recorded feature.
=> fix(geolocation): add altitude to recorded feature coordinates oc: 4838

projects/wm-core/src/services/geoutils.service.ts, projects/wm-core/src/ugc-details/ugc-track-data/ugc-track-data.component.html
- Added *ngIf conditions to display track data only if the values are greater than 0.
chore: Refactor getSlope method to calculate slope from geometry
This commit refactors the getSlope method in the GeoutilsService class to calculate the slope using the geometry of the track. It introduces a new private method, _getSlopeFromGeometry, which calculates the slope based on the altitude difference between consecutive coordinates in the LineString geometry. This change improves code readability and maintainability.
=> chore: Update ugc-track-data.component.html oc: 4826

projects/wm-core/src/modal-ugc-track-uploader/modal-ugc-track-uploader.component.ts, projects/wm-core/src/track-useful-urls/track-useful-urls.component.ts
- Refactored the code to improve serialization of download options in GPX and KML formats.
- Added support for nested properties in GPX format.
- Serialized feature properties as strings in KML format to prevent serialization errors.
chore: Update modal-ugc-track-uploader.component.ts
- Import Feature from geojson
- Add private method _deserializeProperties to deserialize feature properties
- Modify _handleFile method to use _deserializeProperties for LineString features
Refactor track-useful-urls.component.ts to simplify code and improve readability
The code changes in track-useful-urls.component.ts involve refactoring to simplify the code and improve readability. The changes include removing unnecessary lines of code related to metadata and extensions, and restructuring the options …
=> chore(track-useful-urls): improve serialization of download options oc: 4782

projects/wm-core/src/geobox-map/geobox-map.component.ts, projects/wm-core/src/home/home.component.ts, projects/wm-core/src/store/features/ugc/ugc.selector.ts
- Added fallback to uuid property if id is not available.
chore: Update setPoi function in home.component.ts
The setPoi function in home.component.ts has been updated to handle the id parameter correctly. The queryParams object now assigns the id value without converting it to a number when ugcOpened is true. This change ensures that the correct values are passed to the _urlHandlerSvc.updateURL method.
chore: Update currentUgcPoiIDToMap$ type in geobox-map.component.ts
- Updated the type of currentUgcPoiIDToMap$ from Observable<number | null> to Observable<number | string | null>.
- Added support for string values in addition to number values.
- This change allows for more flexibility when mapping UGC POI IDs.
=> chore: Update currentUgcPoiId selector oc: 4855

projects/wm-core/src/services/camera.service.ts, projects/wm-core/src/store/features/ugc/ugc.service.ts, projects/wm-core/src/utils/localForage.ts
- Added a call to the `saveImg` function in the `CameraService` to save an image.
- Added a call to the `saveImg` function in the `UgcService` to save images.
- Updated the `saveApiPoi` and `saveApiTrack` functions in the `UgcService` to use form data for sending data.
- Updated the `syncUgc`, `syncUgcMedias`, `syncUgcPois`, and `syncUgcTracks` functions in the `UgcService` to handle errors during synchronization.
- Removed unnecessary calls to the `saveUgcMedia` function in the `localForage.ts`.
This commit updates the camera and ugc services by adding functionality for saving images, using form data for API requests, handling errors during synchronization, and removing unnecessary code.
=> chore: Update camera and ugc services oc:4764

projects/wm-core/src/pipes/wmtrans.pipe.ts, projects/wm-core/src/track-useful-urls/track-useful-urls.component.ts
Refactor the code to ensure that the first value is always converted to a string before removing any spaces.
chore(pipe): Add support for translating numbers in WmTransPipe
This commit adds a condition to check if the value passed to the pipe is a number. If it is, the number is converted to a string before being translated using the parent TranslatePipe class. This allows for translating numbers in addition to strings in the WmTransPipe.
=> chore: Update track-useful-urls.component.ts oc:4872

projects/wm-core/src/home/home-result/home-result.component.html, projects/wm-core/src/home/home-result/home-result.component.scss, projects/wm-core/src/home/home-result/home-result.component.ts, projects/wm-core/src/store/auth/auth.effects.ts, projects/wm-core/src/store/features/ugc/ugc.effects.ts, projects/wm-core/src/store/features/ugc/ugc.service.ts, projects/wm-core/src/store/user-activity/user-activity.action.ts, projects/wm-core/src/store/user-activity/user-activity.reducer.ts, projects/wm-core/src/store/user-activity/user-activity.selector.ts, projects/wm-core/src/utils/localForage.ts
- Added action "setUgcLoaded" to track UGC loading status
- Updated reducer to handle "setUgcLoaded" action and update the state accordingly
- Added selector "ugcLoaded" to retrieve the UGC loading status from the state
chore: Update home-result.component.html, home-result.component.scss, and home-result.component.ts
- Added loading spinner for ugcOpened state
- Updated styles for the loading spinner
chore(utils): add functions to clear and save ugcLoadedOnce data
This commit adds two new functions to the localForage utility module. The `clearAuthData` function clears the authentication data using the `deviceAuth.clear()` method. The `saveUgcLoadedOnce` function saves the `ugcLoadedOnce` boolean value using the `deviceAuth.setItem()` method. These functions provide convenient ways to …
=> chore: Update user-activity.action.ts, user-activity.reducer.ts, and user-activity.selector.ts oc: 4791

projects/wm-core/src/localization/i18n/de.ts, projects/wm-core/src/localization/i18n/en.ts, projects/wm-core/src/localization/i18n/es.ts, projects/wm-core/src/localization/i18n/fr.ts, projects/wm-core/src/localization/i18n/it.ts, projects/wm-core/src/localization/i18n/pr.ts, projects/wm-core/src/localization/i18n/sq.ts, projects/wm-core/src/store/auth/auth.effects.ts
The `_createErrorAlert` method was returning `null`, which is unnecessary. This commit removes the unused code and returns a promise to create an alert using `_alertCtrl.create()`.
=> chore: Remove unused code in AuthEffects oc:5027

projects/wm-core/src/search-bar/search-bar.component.scss, projects/wm-core/src/search-bar/search-bar.component.ts
- Updated the search-bar component's SCSS file to include a new style for the form element, setting its width to 100%.
- Removed an unused import statement in the search-bar component's TypeScript file.
=> chore: Update search-bar component styles and form width oc:5143

projects/wm-core/src/home/home.component.html, projects/wm-core/src/home/home.component.ts
Added a button to the popup that allows users to return to the home screen. The button is styled as an ion-chip and triggers the `closePopup` method, which dismisses the popup and navigates back to the home content.
=> chore(home): add close popup functionality with button oc: 4786

projects/wm-core/src/box/poi-box/poi-box.component.html, projects/wm-core/src/box/poi-box/poi-box.component.scss, projects/wm-core/src/box/poi-box/poi-box.component.ts, projects/wm-core/src/filters/status-filter/status-filter.component.ts, projects/wm-core/src/home/home-result/home-result.component.ts, projects/wm-core/src/home/home.component.html, projects/wm-core/src/home/home.component.ts, projects/wm-core/src/store/user-activity/user-activity.reducer.ts, projects/wm-core/src/tab-description/tab-description.component.ts
chore: Update status-filter.component.ts and home.component.html
- Added dispatch to goToHome() in resetFilters() method of StatusFilterComponent
- Added dispatch to setMapDetailsStatus({status: 'none'}) in resetFilters() method of StatusFilterComponent
- Removed (resetFiltersEVT)="goToHome()" event binding from wm-status-filter component in home.component.html
chore: Update tab-description.component.ts
- Refactor code to handle null values for descriptionElement and scrollHeight variables.
chore(user-activity): add 'full' option to mapDetailsStatus
This commit adds the 'full' option to the mapDetailsStatus type in the UserActivityState interface of the user-activity.reducer.ts file. This allows for more flexibility in handling the map details status.
chore: Update poi-box component and …
=> chore: update layers view oc: 5201

projects/wm-core/src/filters/status-filter/status-filter.component.scss, projects/wm-core/src/filters/status-filter/status-filter.component.ts, projects/wm-core/src/home/home-result/home-result.component.ts, projects/wm-core/src/store/user-activity/user-activity.action.ts, projects/wm-core/src/store/user-activity/user-activity.effects.ts, projects/wm-core/src/store/user-activity/user-activity.reducer.ts, projects/wm-core/src/track-related-poi/track-related-poi.component.ts
chore: Update status-filter.component.ts and home.component.html
- Added dispatch to goToHome() in resetFilters() method of StatusFilterComponent
- Added dispatch to setMapDetailsStatus({status: 'none'}) in resetFilters() method of StatusFilterComponent
- Removed (resetFiltersEVT)="goToHome()" event binding from wm-status-filter component in home.component.html
chore: Update tab-description.component.ts
- Refactor code to handle null values for descriptionElement and scrollHeight variables.
chore(user-activity): add 'full' option to mapDetailsStatus
This commit adds the 'full' option to the mapDetailsStatus type in the UserActivityState interface of the user-activity.reducer.ts file. This allows for more flexibility in handling the map details status.
chore: Update poi-box component and …
=> chore: update layers view oc: 5203

projects/wm-core/src/store/user-activity/user-activity.reducer.ts
This commit adds a new function called `extractFilterTaxonomies` to the user-activity.reducer.ts file. This function is used to extract filter taxonomies from a given layer object. It filters out any taxonomies with null identifiers and maps them into an array of strings. The extracted filter taxonomies are then used in the setLayer reducer to update the poisSelectedFilterIdentifiers state based on the selected layer's taxonomies. Additionally, when a layer is set to null, the previous layer's filter taxonomies are removed from the poisSelectedFilterIdentifiers state.
Co-authored-by: Z
=> chore(user-activity): add function to extract filter taxonomies oc: 5210

projects/wm-core/src/poi-types-badges/poi-types-badges.component.ts, projects/wm-core/src/store/features/ec/ec.selector.ts, projects/wm-core/src/wm-core.module.ts
This commit adds a new component called PoiTypesBadgesComponent, which is responsible for displaying badges of different POI types. The component takes an input of poiTypes and dynamically generates the badges based on the provided data. Each badge consists of an icon (if available) and the name of the POI type.
The component also includes styling to ensure proper layout and visual representation of the badges. It uses flexbox to arrange the badges in a row with a small gap between them. Each badge has a border, padding, and color defined to make it visually distinct.
Additionally, this commit includes some minor updates to other files:
- ec.selector.ts: Adds temporary arcoded info to currentPoiProperties selector.
- wm-core.module.ts: Imports and declares PoiTypesBadgesComponent in the …
=> chore(poi-types-badges): add component for displaying badges of POI types oc:5275

projects/wm-core/src/releted-pois-navigator/related-pois-navigator.component.ts, projects/wm-core/src/store/features/ec/ec.selector.ts, projects/wm-core/src/wm-core.module.ts
This commit adds the WmRelatedPoisNavigatorComponent to the wm-core module. The component provides navigation buttons for related points of interest (POIs) and displays the current index and count of related POIs. It also updates the URL when navigating to the next or previous related POI.
The commit also includes changes to the ec.selector file, adding selectors for retrieving the current related POI index, count, and IDs of the next and previous related POIs.
Additionally, a new file named related-pois-navigator.component.ts is added, which contains the implementation of the WmRelatedPoisNavigatorComponent.
=> chore: Add WmRelatedPoisNavigatorComponent oc:5289

projects/wm-core/src/image-detail/image-detail.component.html, projects/wm-core/src/image-detail/image-detail.component.scss, projects/wm-core/src/image-detail/image-detail.component.ts, projects/wm-core/src/image-gallery/image-gallery.component.ts, projects/wm-core/src/modal-image/modal-image.component.html, projects/wm-core/src/modal-image/modal-image.component.scss, projects/wm-core/src/modal-image/modal-image.component.ts, projects/wm-core/src/services/url-handler.service.ts, projects/wm-core/src/store/features/ec/ec.actions.ts, projects/wm-core/src/store/features/ec/ec.reducer.ts, projects/wm-core/src/store/features/ec/ec.selector.ts, projects/wm-core/src/store/user-activity/user-activity.effects.ts, projects/wm-core/src/wm-core.module.ts
- Added HTML template for the image detail component
- Added SCSS styles for the image detail component
- Added TypeScript logic for the image detail component
- Imported and declared the ImageDetailComponent in wm-core.module.ts
chore(ec): add support for setting current ec image gallery index
This commit adds support for setting the current ec image gallery index in the URL handler service. It also includes actions, reducer logic, and selectors to handle this new feature.
chore: Update modal-image component
- Removed the ion-slides and related code for image gallery functionality
- Added wm-image-detail component to display image details
- Updated styles to remove gallery-related CSS rules
chore: Update image-gallery.component.ts
- Added import statement for UrlHandlerService
- Updated …
=> chore(image-detail): add image detail component oc: 5298

projects/wm-core/src/services/environment.service.ts
- Added condition to check for shardName in addition to appId when assigning the share link
- If host is found, set the share link to the corresponding key
- If host is not found, generate a new share link based on the appId and shardName
=> chore(environment): update share link logic oc:5401

projects/wm-core/src/features-in-viewport/features-in-viewport.component.html, projects/wm-core/src/features-in-viewport/features-in-viewport.component.scss, projects/wm-core/src/features-in-viewport/features-in-viewport.component.ts, projects/wm-core/src/geobox-map/geobox-map.component.html, projects/wm-core/src/geobox-map/geobox-map.component.ts, projects/wm-core/src/store/conf/conf.reducer.ts, projects/wm-core/src/store/conf/conf.selector.ts, projects/wm-core/src/store/features/ec/ec.actions.ts, projects/wm-core/src/store/features/ec/ec.effects.ts, projects/wm-core/src/store/features/ec/ec.reducer.ts, projects/wm-core/src/store/features/ec/ec.service.ts, projects/wm-core/src/store/features/features.selector.ts, projects/wm-core/src/store/user-activity/user-activity.action.ts, projects/wm-core/src/store/user-activity/user-activity.effects.ts, projects/wm-core/src/store/user-activity/user-activity.reducer.ts, projects/wm-core/src/store/user-activity/user-activity.selector.ts, projects/wm-core/src/tab-description/tab-description.component.scss, projects/wm-core/src/types/config.ts, projects/wm-core/src/wm-core.module.ts
This commit adds the features-in-viewport component, which displays a list of features in a slide show format. The component template and styles are also included.
chore: Update geobox-map.component.html and geobox-map.component.ts
- Added class "show-bottom-features" to the div element in geobox-map.component.html
- Added input property "enableFeaturesInViewport$" and event listener "featuresInViewport()" in geobox-map.component.ts
chore: Update user-activity actions and reducer
This commit updates the user-activity.actions.ts file by adding a new action called "wmMapFeaturesInViewport". It also updates the user-activity.reducer.ts file by adding a new case for this action, which sets the "featuresInViewport" property in the state. Additionally, it adds new selectors in the …
=> chore: Add features-in-viewport component oc: 5363

projects/wm-core/src/geobox-map/geobox-map.component.html, projects/wm-core/src/geobox-map/geobox-map.component.ts, projects/wm-core/src/slope-chart/slope-chart.component.scss
- change reloadCustomTracks binding to check if currentCustomTrack$ is null
- remove unused reloadCustomTrack method and associated BehaviorSubject
💄 style(slope-chart): adjust slope chart styling
- remove unnecessary width property from wm-slope-chart selector
=> 🐛 fix(geobox-map): update reloadCustomTracks condition oc:5581

projects/wm-core/src/draw-ugc-button/draw-ugc-button.component.html, projects/wm-core/src/draw-ugc-button/draw-ugc-button.component.scss, projects/wm-core/src/draw-ugc-button/draw-ugc-button.component.ts, projects/wm-core/src/draw-ugc/draw-ugc.component.html, projects/wm-core/src/draw-ugc/draw-ugc.component.scss, projects/wm-core/src/draw-ugc/draw-ugc.component.ts, projects/wm-core/src/geobox-map/geobox-map.component.html, projects/wm-core/src/geobox-map/geobox-map.component.ts, projects/wm-core/src/localization/i18n/de.ts, projects/wm-core/src/localization/i18n/en.ts, projects/wm-core/src/localization/i18n/es.ts, projects/wm-core/src/localization/i18n/fr.ts, projects/wm-core/src/localization/i18n/it.ts, projects/wm-core/src/localization/i18n/pr.ts, projects/wm-core/src/localization/i18n/sq.ts, projects/wm-core/src/modal-ugc-uploader/modal-ugc-uploader.component.ts, projects/wm-core/src/store/conf/conf.reducer.ts, projects/wm-core/src/store/conf/conf.selector.ts, projects/wm-core/src/store/features/ugc/ugc.actions.ts, projects/wm-core/src/store/features/ugc/ugc.effects.ts, projects/wm-core/src/store/features/ugc/ugc.reducer.ts, projects/wm-core/src/store/features/ugc/ugc.selector.ts, projects/wm-core/src/store/user-activity/user-activity.action.ts, projects/wm-core/src/store/user-activity/user-activity.effects.ts, projects/wm-core/src/store/user-activity/user-activity.selector.ts, projects/wm-core/src/types/config.ts, projects/wm-core/src/utils/features.ts, projects/wm-core/src/wm-core.module.ts
Implemented a new component, `WmDrawUgcButtonComponent`, for drawing user-generated content. This includes buttons to toggle drawing modes (POI and Track) and to handle user authentication for drawing features. Added relevant HTML, SCSS, and TypeScript files for the new component. Updated the map component to use the new drawing button component, replacing the previous draw track button logic.
Additionally, modified the configuration selectors and reducers to manage new states related to drawing features and user activity actions. Updated effects to handle the opening of login modals and dispatching of actions related to drawing features. Updated the configuration interface to include a new property for showing draw POI features.
=> chore(draw-ugc): ✨ add "draw user-generated content" component oc:5569

projects/wm-core/src/types/config.ts
Added a new optional boolean property `show_track_direction_arrow` to the `IMAP` interface. This property allows configuration for displaying direction arrows on tracks.
=> feat(config): ✨ add show_track_direction_arrow option to IMAP interface oc: 5743

projects/wm-core/src/geobox-map/geobox-map.component.html, projects/wm-core/src/geobox-map/geobox-map.component.ts, projects/wm-core/src/store/conf/conf.selector.ts, projects/wm-core/src/types/config.ts
Introduced the ability to zoom features within the viewport in the Geobox Map component.
- Added `[wmMapLayerZoomFeaturesInViewport]` binding to the HTML template.
- Implemented `zoomFeaturesInViewport$` observable in the component TypeScript file.
- Created a `confZoomFeaturesInViewport` selector to fetch min and max zoom settings from the store.
- Updated the `IOPTIONS` interface to include `maxZoomFeaturesInViewport` and `minZoomFeaturesInViewport` properties.
This enhancement allows for better control over feature visibility at different zoom levels, enhancing the user's map interaction experience.
=> feat(map): ✨ add zoom features in viewport functionality oc:5742

projects/wm-core/src/get-directions/get-directions.component.ts, projects/wm-core/src/localization/i18n/de.ts, projects/wm-core/src/localization/i18n/en.ts, projects/wm-core/src/localization/i18n/es.ts, projects/wm-core/src/localization/i18n/fr.ts, projects/wm-core/src/localization/i18n/it.ts, projects/wm-core/src/localization/i18n/pr.ts, projects/wm-core/src/localization/i18n/sq.ts, projects/wm-core/src/modal-get-directions/modal-get-directions.component.ts, projects/wm-core/src/services/geolocation.service.ts, projects/wm-core/src/store/features/features.selector.ts, projects/wm-core/src/store/user-activity/user-activity.action.ts, projects/wm-core/src/store/user-activity/user-activity.effects.ts, projects/wm-core/src/store/user-activity/user-activity.reducer.ts, projects/wm-core/src/store/user-activity/user-activity.selector.ts, projects/wm-core/src/wm-core.module.ts
Added functionality to dispatch the current location to the store using NgRx. This allows for better state management of the geolocation data.
- Removed unused `defaultIfEmpty` import from `rxjs/operators`.
- Added `setCurrentLocation` action in `user-activity.action.ts`.
- Updated `UserActivityState` and `userActivityReducer` to include `currentLocation`.
- Modified selectors to use the current location from the store.
- Updated `GeolocationService` to dispatch the current location to the store when it changes.
TODO: Refactor to use the `currentLocation` from the store instead of `onLocationChange`.
=> chore(geolocation): 🌐 integrate current location with store oc:5741

projects/wm-core/src/store/features/ec/ec.effects.ts
Added distinctUntilChanged operator to the featuresInViewport$ effect to prevent redundant emissions when feature IDs have not changed. This ensures that only significant changes in the feature IDs trigger further processing, enhancing performance by avoiding unnecessary operations.
The distinctUntilChanged operator compares the previous and current feature ID arrays and only allows the stream to proceed if there is a change in the array length or the content of the arrays.
=> chore(ec): ✨ add distinctUntilChanged to featuresInViewport$ effect oc:5794

projects/wm-core/src/form/form.component.html, projects/wm-core/src/form/form.component.ts
Enhanced the form component to auto-select the title field text on first click and to set a default timestamp value if no value is provided.
- Added a click event to the title input field to trigger text selection upon the first click.
- Introduced a private flag `_titleFirstClick` to ensure the behavior occurs only once per session.
- Implemented logic to assign a default timestamp to the title field when a value is not provided. The format is "id YYYY/MM/DD HH:MM", leveraging the current date and time.
=> chore(form): ✨ add auto-select and default timestamp for title field oc:5576

projects/wm-core/src/image-picker/image-picker.component.html, projects/wm-core/src/image-picker/image-picker.component.ts, projects/wm-core/src/store/features/ugc/ugc.service.ts, projects/wm-core/src/ugc-poi-properties/ugc-poi-properties.component.html, projects/wm-core/src/ugc-poi-properties/ugc-poi-properties.component.ts, projects/wm-core/src/ugc-track-properties/ugc-track-properties.component.html, projects/wm-core/src/ugc-track-properties/ugc-track-properties.component.ts
Enhanced the `WmImagePickerComponent` to support `readonlyPhotos` input, allowing pre-existing photos to be displayed and managed separately from newly added photos. This ensures that photos with an `id` are treated as immutable and not duplicated when adding new photos.
Changes include:
- Updated `image-picker.component.html` to conditionally display the remove icon only for photos without an `id`.
- Introduced `readonlyPhotos` input and a `showPhotos$` observable for better photo management in `image-picker.component.ts`.
- Modified `ugc.service.ts` to filter out photos with an `id` before processing.
- Updated UGC POI and Track property components to integrate the image picker with the new `readonlyPhotos` functionality, ensuring that `media` property is correctly updated with changes. …
=> chore(image-picker): ✨ add readonlyPhotos support and improve photo handling oc:5240

projects/wm-core/src/store/auth/auth.effects.ts, projects/wm-core/src/store/auth/auth.service.ts
Convert the email to lowercase before passing it to the login and sign-up methods to ensure consistency and prevent issues related to case-sensitivity. This change helps in avoiding potential mismatches or errors when users input their email in different cases.
=> fix(auth): 🐛 ensure email is in lowercase during login and signup oc:5238

projects/wm-core/src/store/features/ugc/ugc.service.ts
Introduced a new method to clean EXIF data from special characters before sending it. This ensures that any Unicode characters which may cause issues are removed. This update includes:
- A `_cleanExifData` method to iterate over media properties and clean EXIF data.
- A `_cleanObject` helper function to recursively clean invalid Unicode characters from strings and objects.
=> chore(ugc): ✨ add EXIF data cleaning feature to remove special characters oc:5926

karma.conf.js, package.json, projects/wm-core/src/store/features/ugc/ugc.service.spec.ts
Introduced Karma configuration to the project to enable unit testing with Jasmine and Angular testing utilities. Added initial unit tests for the `UgcService`, focusing on EXIF data cleaning and `FormData` building functionalities.
- Added `karma.conf.js` for Karma setup with necessary plugins.
- Updated `package.json` with test scripts for running tests via Karma.
- Created `ugc.service.spec.ts` to implement tests for the `UgcService`.
These additions enhance the project's testability by providing a framework and initial test cases for verifying the functionality of the UGC service.
=> chore(testing): ✨ add Karma configuration and initial unit tests for UGC service oc:5927

projects/wm-core/src/form/form.component.html, projects/wm-core/src/form/form.component.ts
Added a new method `capitalizeTitle` to the `WmFormComponent` to automatically capitalize the first letter of the title field when the `ionChange` event is triggered. This ensures that the title always starts with an uppercase letter if the user starts typing in lowercase. The method updates the form control value without emitting an additional event.
=> chore(form): ✨ add automatic title capitalization on ionChange event oc:5251

projects/wm-core/src/features-in-viewport/features-in-viewport.component.html, projects/wm-core/src/features-in-viewport/features-in-viewport.component.ts
Changed sliderOptions to an observable sliderOptions$ to dynamically adjust slide settings based on the number of features in the viewport. This allows for different configurations when there is only one feature compared to multiple features. The adjustment includes changes to properties like `slidesPerView`, `spaceBetween`, `slidesOffsetBefore`, `slidesOffsetAfter`, and `centeredSlides`.
=> refactor(features-in-viewport): 🔄 make sliderOptions observable oc:6000

projects/wm-core/src/geobox-map/geobox-map.component.html, projects/wm-core/src/geobox-map/geobox-map.component.ts, projects/wm-core/src/services/geolocation.service.ts, projects/wm-core/src/store/features/features.selector.ts, projects/wm-core/src/store/user-activity/user-activity.action.ts, projects/wm-core/src/store/user-activity/user-activity.effects.ts, projects/wm-core/src/store/user-activity/user-activity.reducer.ts, projects/wm-core/src/store/user-activity/user-activity.selector.ts
Added new functionalities to the geobox map component including focus position and recording panel toggles. Updated HTML to bind new observables for map control parameters. Refactored TypeScript to manage state and integrate with GeolocationService. Introduced new actions and effects for handling recording state and focus position. Modified reducer and selectors to manage corresponding states.
- Added `[wmMapDisableFitView]` and `[wmMapGeojson]` bindings to HTML.
- Introduced `focusPosition$`, `enableRecoderPanel$`, and `recordedTrack$` observables.
- Updated GeolocationService to dispatch actions for recording state changes.
- Created new actions: `setEnableRecoderPanel`, `setOnRecord`, and `setFocusPosition`.
- Added effects to handle side effects of recording state changes.
- Enhanced …
=> chore(map): 🗺️ add focus position and recording panel functionality oc: 5239

projects/wm-core/src/geobox-map/geobox-map.component.html, projects/wm-core/src/geobox-map/geobox-map.component.ts, projects/wm-core/src/store/features/features.selector.ts, projects/wm-core/src/store/user-activity/user-activity.action.ts, projects/wm-core/src/store/user-activity/user-activity.reducer.ts, projects/wm-core/src/store/user-activity/user-activity.selector.ts
Corrected the typo in variable names from "Recoder" to "Recorder" across the component HTML and TypeScript files. Introduced new observables and actions for enabling track and POI recorder panels. Updated selectors and reducers accordingly to manage the new state variables and ensure proper functionality. This refactor improves code readability and functionality by accurately representing the feature's purpose and enhancing the component's capabilities.
=> fix(geobox-map): 🐛 correct typo in variable names and add new functionality oc:6003

projects/wm-core/src/geobox-map/geobox-map.component.html, projects/wm-core/src/geobox-map/geobox-map.component.ts, projects/wm-core/src/localization/i18n/de.ts, projects/wm-core/src/localization/i18n/en.ts, projects/wm-core/src/localization/i18n/es.ts, projects/wm-core/src/localization/i18n/fr.ts, projects/wm-core/src/localization/i18n/it.ts, projects/wm-core/src/localization/i18n/pr.ts, projects/wm-core/src/localization/i18n/sq.ts, projects/wm-core/src/store/features/features.selector.ts, projects/wm-core/src/store/user-activity/user-activity.action.ts, projects/wm-core/src/store/user-activity/user-activity.reducer.ts, projects/wm-core/src/store/user-activity/user-activity.selector.ts
This update introduces the ability to download map tiles by managing bounding boxes. Users can now select areas on the map for downloading tiles. The feature includes:
- UI elements for enabling tile downloads and displaying bounding boxes.
- Functions for setting bounding boxes and disabling/enabling download buttons.
- A delete confirmation dialog for removing bounding boxes with multi-language support.
- State management for enabling and disabling tile downloads, handling bounding boxes, and related UI changes.
- Updated localization files to support new strings in multiple languages.
=> chore(map): 🌍 add tile download feature with bounding box management oc:5578

projects/wm-core/src/box/search-box/search-box.component.html, projects/wm-core/src/filters/filters.component.html, projects/wm-core/src/filters/filters.component.scss, projects/wm-core/src/filters/filters.module.ts, projects/wm-core/src/filters/select-filter/select-filter.component.html, projects/wm-core/src/filters/select-filter/select-filter.component.scss, projects/wm-core/src/filters/select-filter/select-filter.component.ts, projects/wm-core/src/filters/status-filter/status-filter.component.html, projects/wm-core/src/filters/status-filter/status-filter.component.scss, projects/wm-core/src/poi-types-badges/poi-types-badges.component.ts, projects/wm-core/src/shared/shared.module.ts, projects/wm-core/src/store/conf/conf.reducer.ts, projects/wm-core/src/tab-howto/tab-howto.component.html, projects/wm-core/src/tab-howto/tab-howto.component.scss, projects/wm-core/src/tab-howto/tab-howto.component.ts, projects/wm-core/src/track-related-poi/track-related-poi.component.html, projects/wm-core/src/track-related-poi/track-related-poi.component.scss, projects/wm-core/src/track-related-poi/track-related-poi.component.ts, projects/wm-core/src/wm-icon/wm-icon.component.ts
Replaced inline SVG rendering logic in multiple components with a reusable `wm-icon` component to streamline icon handling. This change affects several components including `search-box`, `filters`, `select-filter`, `status-filter`, `poi-types-badges`, `tab-howto`, and `track-related-poi`.
- Introduced `wm-icon` component with logic to select and render icons based on data.
- Removed redundant SVG rendering logic from the affected components.
- Updated the respective HTML and SCSS files to accommodate the changes.
- Added `WmIconComponent` to `WmSharedModule`.
These changes aim to reduce code duplication and improve maintainability by centralizing icon rendering logic.
=> refactor(icons): ♻️ convert svg rendering to wm-icon component oc:6351
