filters/select-filter/select-filter.component.html, filters/select-filter/select-filter.component.scss
chore: Update select-filter component HTML and SCSS
- Removed the display of the count of pois in the select-filter header
- Added a new span element to display the count of pois or tracks, depending on the filter type
- Updated the SCSS file to style the new count element
Refs: #1858
=> sardegna_improvements

projects/wm-core/src/store/conf/conf.selector.ts, projects/wm-core/src/types/config.ts
Added the PRIVACY field to the confFeature selector and ICONF interface for better configuration handling.
=> chore: Add PRIVACY field to confFeature selector and ICONF interface

projects/wm-core/src/store/api/api.service.ts, projects/wm-core/src/store/conf/conf.service.ts
- Removed the private _hostToGeohubAppId object from api.service.ts and conf.service.ts
- Added a new export const hostToGeohubAppId object in api.service.ts
- Updated references to _hostToGeohubAppId with hostToGeohubAppId in both files
=> chore: Update hostToGeohubAppId in api.service.ts and conf.service.ts

package.json, projects/wm-core/src/services/geolocation.service.ts
- Updated package.json to include "@capacitor/app" version "^6.0.0"
- Modified geolocation.service.ts to add functionality for handling app state changes and updating watcher options based on accuracy level
=> chore: Update dependencies and geolocation service oc: 4196

projects/wm-core/src/services/camera.service.ts, projects/wm-core/src/services/device.service.ts
- Added WmDeviceInfo interface to MediaProperties import
- Updated CameraService to include device information when capturing photos
- Updated CameraService to include device information when saving photos
- Updated CameraService to include device information when uploading photos
- Added getInfo() method in DeviceService to retrieve device information
=> chore: Update camera and device services oc:4273

projects/wm-core/src/box/box.module.ts, projects/wm-core/src/box/poi-box/poi-box.component.html, projects/wm-core/src/box/search-box/search-box.component.html, projects/wm-core/src/box/udpated-at/updated-at.component.html, projects/wm-core/src/box/udpated-at/updated-at.component.scss, projects/wm-core/src/box/udpated-at/updated-at.component.ts, projects/wm-core/src/home/home-result/home-result.component.html, projects/wm-core/src/pipes/pipe.module.ts, projects/wm-core/src/pipes/wm-sort.pipe.ts, projects/wm-core/src/services/camera.service.ts, projects/wm-core/src/store/features/ugc/ugc.effects.ts
feat(box): add UpdatedAtComponent
- Added the UpdatedAtComponent to display the updated date and time in the box module.
- Created the HTML template and SCSS file for the UpdatedAtComponent.
- Implemented the logic in the UpdatedAtComponent TypeScript file to receive and display the updated date.
chore: Add WmSortPipe to pipe module
This commit adds the WmSortPipe to the pipe module in order to enable sorting functionality. The WmSortPipe is a new file that implements the PipeTransform interface and provides a transform method for sorting an array based on a specified field.
chore: Add updated timestamp to poi-box and search-box components
- Added a new ng-container in poi-box.component.html to display the updated timestamp using wm-updated-at component.
- Added a new ng-container in …
=> chore: Sorting UgcTrack and UgcPoi by date oc: 4453

projects/wm-core/src/store/features/ugc/ugc.effects.ts, projects/wm-core/src/ugc-medias/modal-media/wm-modal-media.component.html, projects/wm-core/src/ugc-medias/modal-media/wm-modal-media.component.scss, projects/wm-core/src/ugc-medias/modal-media/wm-modal-media.component.ts, projects/wm-core/src/ugc-medias/wm-ugc-medias.component.html, projects/wm-core/src/ugc-medias/wm-ugc-medias.component.scss, projects/wm-core/src/ugc-medias/wm-ugc-medias.component.ts, projects/wm-core/src/ugc-medias/wm-ugc-medias.module.ts, projects/wm-core/src/wm-core.module.ts
This commit updates the ugc.effects.ts file to include a new method for syncing UGC medias. Previously, only tracks and pois were being synced, but now the code has been modified to also sync medias. This change ensures that all UGC data is properly synchronized.
feat: Add ugc-medias module and modal-media component
- Added new files for the ugc-medias module and modal-media component
- Created HTML template, SCSS styles, and TypeScript code for the modal-media component
- Created HTML template, SCSS styles, and TypeScript code for the ugc-medias component
- Imported necessary modules and components in wm-core.module.ts
=> chore: Update ugc.effects.ts to sync UGC medias oc: 4550

projects/wm-core/src/track-properties/track-properties.component.html
- Add class "ion-no-border" to ion-header element for styling consistency.
=> chore: Update track-properties.component.html

projects/wm-core/src/store/features/ugc/ugc.effects.ts
- Added currentUgcPoi and currentUgcTrack imports to ugc.effects.ts
- Added closeUgcEffect$ effect to handle closing of UGC
- Updated currentUgcPoi$ effect to include currentUgcPoiId action
=> chore: Update ugc.effects.ts oc: 4644

projects/wm-core/src/store/features/ugc/ugc.service.ts, projects/wm-core/src/ugc-medias/wm-ugc-medias.component.ts
- Fix a bug in ugc.service.ts where the comparison of media properties was incorrect.
- Fix a bug in wm-ugc-medias.component.ts where the logic for retrieving ugc medias was not handling photos correctly.
=> chore: Update ugc.service.ts and wm-ugc-medias.component.ts oc: 4659

projects/wm-core/src/login/login.component.scss
- Added height and flex properties to the login form for better layout
- Changed the display property of the buttons container to flex and adjusted its alignment
=> chore: Update login component styles oc: 4775

projects/wm-core/src/ugc-poi-properties/ugc-poi-properties.component.html, projects/wm-core/src/ugc-poi-properties/ugc-poi-properties.component.scss, projects/wm-core/src/ugc-track-properties/ugc-track-properties.component.html, projects/wm-core/src/ugc-track-properties/ugc-track-properties.component.scss
- Added ion-grid to the buttons section for better layout
- Updated button styles in the component's SCSS file
=> chore: Update ugc-poi-properties and ugc-track-properties components oc: 4756

projects/wm-core/src/modal-ugc-track-uploader/modal-ugc-track-uploader.component.html, projects/wm-core/src/modal-ugc-track-uploader/modal-ugc-track-uploader.component.scss, projects/wm-core/src/modal-ugc-track-uploader/modal-ugc-track-uploader.component.ts
- Added a new map component to display the track
- Updated the form component to initialize with track properties
- Updated the SCSS file to style the map component
=> chore: Update modal-ugc-track-uploader component oc:4778, 4779

projects/wm-core/src/form/form.component.html, projects/wm-core/src/form/form.component.scss
Updated the form component's HTML structure for better readability and organization. Introduced new CSS classes to improve the visual presentation of form titles and items. Adjusted item alignment and spacing for a more user-friendly interface.
=> chore(form): enhance form layout and styling oc: 4806

projects/wm-core/src/slope-chart/slope-chart.component.scss, projects/wm-core/src/ugc-medias/wm-ugc-medias.component.scss, projects/wm-core/src/ugc-track-properties/ugc-track-properties.component.scss
- Changed padding to margin in slope-chart.component.scss
- Added empty state styling in wm-ugc-medias.component.scss
- Adjusted width and padding in ugc-track-properties.component.scss
=> chore: Update slope-chart, ugc-medias, and ugc-track-properties component styles oc:4837

projects/wm-core/src/localization/i18n/de.ts, projects/wm-core/src/localization/i18n/en.ts, projects/wm-core/src/localization/i18n/es.ts, projects/wm-core/src/localization/i18n/fr.ts, projects/wm-core/src/localization/i18n/it.ts, projects/wm-core/src/localization/i18n/pr.ts, projects/wm-core/src/localization/i18n/sq.ts, projects/wm-core/src/store/user-activity/user-activity.selector.ts, projects/wm-core/src/track-properties/track-properties.component.html, projects/wm-core/src/track-properties/track-properties.component.ts
- Refactored the flowLineQuoteText selector in user-activity.selector.ts to return an object with the flow_line_quote_orange, flow_line_quote_red, and html properties.
- Updated track-properties.component.html to use the new flowLineQuoteHtml$ observable instead of flowLineQuoteText$.
- Added a new observable, flowLineQuoteHtml$, in track-properties.component.ts that translates the html property from the flowLineQuoteText object and replaces placeholders with actual values.
chore: Update localization files
- Updated translations for German, English, Spanish, French, and Italian languages.
- Added new translations for various phrases and terms.
- Improved accuracy and clarity of existing translations.
=> chore: Update user-activity.selector.ts and track-properties.component.html oc: 5015

projects/wm-core/src/shared/ugc-synchronized-badge/ugc-synchronized-badge.component.ts
- Removed color attribute from ion-icons
- Added custom colors for cloud-done-outline and cloud-offline-outline icons
=> chore: Update ugc-synchronized-badge component

projects/wm-core/src/login/login.component.html, projects/wm-core/src/login/login.component.ts, projects/wm-core/src/services/environment.service.ts
This commit adds a new `shareLink` property to the `EnvironmentService` class. The `shareLink` is assigned based on the host value from the environment redirects, or it defaults to `${this.appId}.app.webmapp.it`. This property allows for easy access to the share link in the application.
=> chore(environment): add shareLink property

projects/wm-core/src/box/search-box/search-box.component.html, projects/wm-core/src/box/search-box/search-box.component.scss, projects/wm-core/src/home/home-layer/home-layer.component.html, projects/wm-core/src/home/home-result/home-result.component.html, projects/wm-core/src/home/home-result/home-result.component.ts, projects/wm-core/src/home/home.component.html, projects/wm-core/src/home/home.component.ts, projects/wm-core/src/localization/i18n/de.ts, projects/wm-core/src/localization/i18n/en.ts, projects/wm-core/src/localization/i18n/es.ts, projects/wm-core/src/localization/i18n/fr.ts, projects/wm-core/src/localization/i18n/it.ts, projects/wm-core/src/localization/i18n/pr.ts, projects/wm-core/src/localization/i18n/sq.ts, projects/wm-core/src/services/url-handler.service.ts, projects/wm-core/src/tab-description/tab-description.component.ts, projects/wm-core/src/types/elastic.ts
chore: Update search-box component HTML and SCSS
- Added translations for "Lunghezza" and "Distanza da te"
- Updated styling for search box properties to include a dot separator
chore: Update home-layer.component.html and tab-description.component.ts
- Refactored the HTML template in home-layer.component.html to use wm-tab-description component instead of a div for description display.
- Removed AfterViewChecked interface implementation from WmTabDescriptionComponent class in tab-description.component.ts as it was not being used.
- Added an interval check in _checkIfContentIsTruncated() method to ensure that scrollHeight is calculated correctly before checking if content is truncated.
chore: Update setTrack and setPoi methods in UrlHandlerService
- Refactored the setTrack and setPoi …
=> chore: update layers view oc: 5162

projects/wm-core/src/inner-html/inner-html.component.html, projects/wm-core/src/inner-html/inner-html.component.scss, projects/wm-core/src/inner-html/inner-html.component.ts, projects/wm-core/src/store/features/ec/ec.selector.ts
This commit adds a new component called WmEmbeddedElementComponent. This component is responsible for rendering an embedded element with a title and HTML content. It uses Angular's DomSanitizer to bypass security and display the HTML content safely. The component also includes styling for the title and the embedded element container.
The WmEmbeddedElementComponent is imported and declared in the WmCoreModule, making it available for use in other parts of the application.
The commit also includes an example usage of the WmEmbeddedElementComponent in the ec.selector.ts file, where an embedded element with a title and HTML content is added to a feature object.
This change enhances the functionality of the application by allowing the display of embedded elements with dynamic content.
=> chore(embedded-element): add embedded element component oc:5441

projects/wm-core/src/image-detail/image-detail.component.html, projects/wm-core/src/image-detail/image-detail.component.scss, projects/wm-core/src/image-detail/image-detail.component.ts, projects/wm-core/src/image-gallery/image-gallery.component.html, projects/wm-core/src/image-gallery/image-gallery.component.scss, projects/wm-core/src/image-gallery/image-gallery.component.ts, projects/wm-core/src/store/conf/conf.reducer.ts, projects/wm-core/src/store/conf/conf.selector.ts, projects/wm-core/src/types/config.ts
- Added ion-text element to display the image name in the image-detail component
- Updated styling of the image-detail component to align items to flex-start
- Added ion-text element to display the image name in the image-gallery component
- Updated styling of the image-gallery component to adjust slide width and font size
chore: Update image detail and image gallery components
- Updated the condition for displaying the image name in the image-detail.component.html and image-gallery.component.html files to include the configuration option "showMediaName".
- Added import statements for confOPTIONS and IOPTIONS in the image-detail.component.ts and image-gallery.component.ts files.
- Added confOPTIONS$ observable in both components to select the value of confOPTIONS from the store.
- Added …
=> chore: Update image detail and image gallery components oc:5440

projects/wm-core/src/store/conf/conf.reducer.ts
Refactor the conf reducer to efficiently update controls data by fixing a variable assignment issue.
=> chore: refactor conf reducer to update controls data efficiently oc: 5468

projects/wm-core/src/store/auth/auth.effects.ts
update deleteUser effect, clear user data when delete a logged user
=> chore: update deleteUser effect

projects/wm-core/src/form/form.component.html, projects/wm-core/src/localization/i18n/de.ts, projects/wm-core/src/localization/i18n/en.ts, projects/wm-core/src/localization/i18n/es.ts, projects/wm-core/src/localization/i18n/fr.ts, projects/wm-core/src/localization/i18n/it.ts, projects/wm-core/src/localization/i18n/pr.ts, projects/wm-core/src/localization/i18n/sq.ts, projects/wm-core/src/ugc-details/ugc-track-data/ugc-track-data.component.html, projects/wm-core/src/ugc-poi-properties/ugc-poi-properties.component.ts, projects/wm-core/src/ugc-track-properties/ugc-track-properties.component.ts
=> chore: adding new translations oc: 5454

projects/wm-core/src/box/layer-box/layer-box.component.scss, projects/wm-core/src/box/ugc-box/ugc-box.component.scss, projects/wm-core/src/home/home.component.ts, projects/wm-core/src/services/url-handler.service.ts
- Open map-detail on setUgc (home.component)
- Manage removeLatest with ugc (url-handler.service)
=> chore: manage mapDetails with ugc oc:5228

projects/wm-core/src/image-picker/image-picker.component.html, projects/wm-core/src/image-picker/image-picker.component.scss, projects/wm-core/src/image-picker/image-picker.component.ts, projects/wm-core/src/localization/i18n/de.ts, projects/wm-core/src/localization/i18n/en.ts, projects/wm-core/src/localization/i18n/es.ts, projects/wm-core/src/localization/i18n/fr.ts, projects/wm-core/src/localization/i18n/it.ts, projects/wm-core/src/localization/i18n/pr.ts, projects/wm-core/src/localization/i18n/sq.ts, projects/wm-core/src/services/camera.service.ts, projects/wm-core/src/wm-core.module.ts
- implement image picker component with HTML, SCSS, and TypeScript
- allow users to select and display up to 3 photos from the gallery
- utilize camera service for photo retrieval
🌐 i18n(localization): add translations for image picker
- update translations in DE, EN, ES, FR, IT, PR, and SQ locales
- include phrases related to the image picker functionality
♻️ refactor(camera service): simplify photo retrieval logic
- remove unnecessary checks and streamline permission handling
- optimize gallery photo retrieval process
🔧 chore(module): register image picker component in module
- add WmImagePickerComponent to wm-core module declarations
=> 🔧 chore(image-picker): add new image picker component oc:5435

projects/wm-core/src/image-picker/image-picker.component.scss, projects/wm-core/src/modal-ugc-uploader/modal-ugc-uploader.component.html, projects/wm-core/src/modal-ugc-uploader/modal-ugc-uploader.component.scss, projects/wm-core/src/modal-ugc-uploader/modal-ugc-uploader.component.ts, projects/wm-core/src/store/user-activity/user-activity.effects.ts, projects/wm-core/src/utils/features.ts, projects/wm-core/src/utils/form.ts, projects/wm-core/src/utils/localForage.ts, projects/wm-core/src/wm-core.module.ts
- rename ModalUgcTrackUploaderComponent to ModalUgcUploaderComponent
- update component logic to handle both track and poi features
- add photo handling capabilities
- adjust form and geometry handling functions
🔧 chore(component): add support for point geometry and photo uploads
- introduce Point geometry support in feature processing
- add methods for photo handling and validation
♻️ refactor(styles): update styles for modal-ugc-uploader component
- rename styles to match new component name
- add styling for map container and padding adjustments
💄 style(image-picker): enhance border style with fallback
- add fallback colors for border variables to ensure consistency across themes
=> ♻️ refactor(component): rename and update ugc uploader component oc:5582

projects/wm-core/src/store/features/ugc/ugc.effects.ts
Enhanced the `updateUgcPoi$` effect by integrating the latest drawn geometry into the UGC POI update process. The effect now:
- Imports `currentUgcPoiDrawnGeometry` from the UGC selector.
- Uses `withLatestFrom` to combine the update action with the current drawn geometry.
- Constructs an updated POI object, ensuring the geometry is included.
- Updates the POI using the `updateApiPoi` service with the newly constructed object.
- Ensures the success action reflects the updated POI.
=> refactor(ugc): ♻️ update UGC POI with drawn geometry oc_5655

projects/wm-core/src/tab-howto/tab-howto.component.html
Introduces visual indicators for activities such as touring bike, road bike, mountain bike, e-bike, nordic walking, and more.
Enhances user experience by visually distinguishing different modes of walkability.
This update aligns with the new design standards for better category representation.
=> chore: add new walkability icons for various activities oc: 5714

projects/wm-core/src/form/form.component.html, projects/wm-core/src/form/form.component.scss, projects/wm-core/src/localization/i18n/de.ts, projects/wm-core/src/localization/i18n/en.ts, projects/wm-core/src/localization/i18n/es.ts, projects/wm-core/src/localization/i18n/fr.ts, projects/wm-core/src/localization/i18n/it.ts, projects/wm-core/src/localization/i18n/pr.ts, projects/wm-core/src/localization/i18n/sq.ts
Updated the form component to conditionally display the form field based on the number of available forms. The form field will only be shown if there is more than one form available. This change improves the user interface by preventing unnecessary form field displays when there is only a single form option.
=> chore(form): ✨ add conditional display of form field oc:5247
